Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -42,6 +42,9 @@ jobs:
         run: |
           nohup mlflow ui --host 0.0.0.0 --port 5000 &  # Run MLflow UI in the background
           sleep 5  # Wait for a moment to let the server starts
+      - name: Verify MLflow is running
+        run: |
+          curl -sSf http://127.0.0.1:5000 || (echo "MLflow failed to start" && exit 1)
       - name: Model Building
         env:
           HF_TOKEN: ${{ secrets.HF_TOKEN }}
